export const LOGO_BACKGROUND_BY_ID: Readonly<Record<string, string>> = {
  'clube-finlandia': '#FFFFFF',
  'lelu-museu': '#FFFFFF',
  'gute-passeios': '#FCED1E',
  'expedicao-raizes': '#000000',
  'esquilo-passeios': '#000000',
  'jipe-tour': '#FDFDFD',
  'aguia-de-penedo': '#FEFEFE',
  'rota-dos-passeios': '#FAFAFA',
  'trilhando-penedo': '#FFFFFF',
  'hotel-bertell': '#E4E2E3',
  'hotel-britannia': '#FFFFFF',
  'hotel-casa-encantada': '#1B4436',
  'hotel-da-cachoeira': '#000000',
  'hotel-daniela': '#FFFFFF',
  'hotel-girassol': '#FFFFFF',
  'hotel-rio-penedo': '#949492',
  'hotel-do-sino': '#000000',
  'hotel-terras-finlandia': '#FEFEFE',
  'hotel-titanic': '#2F2E2C',
  'pousada-casa-do-bosque': '#FFFFFF',
  'pousada-chez-nous': '#FFFFFF',
  'pousada-lago': '#000000',
  'pousada-penedo': '#FFFFFF',
  'pousada-santa-fe': '#013332',
  'pousada-serra-da-india': '#F6F6F6',
  'pousada-do-sol': '#F2EDE7',
  'pousada-terraco': '#FFFFFF',
  'vert-hotel': '#6F6534',
  'vila-francesa-hotel': '#0171B1',
  'pousada-doce-mel': '#1C0D05',
  'le-garden-pousada-boutique': '#FFFFFF',
  'pousada-viking': '#FCFCFC',
  'halloween-inn-penedo': '#FFFFFF',
  'pousada-nova-conquista': '#F6C423',
  'recanto-dos-passaros-penedo': '#FEFEFE',
  'pousada-laponia': '#F2EDE7',
  'vilar-hotel': '#2D2C3C',
  'hotel-penedo-inn': '#000000',
  'chale-na-roca-penedo': '#FFFFFF',
  'pousada-chicle-penedo-mc': '#FFFFFF',
  'pousada-estancia-penedo': '#FFFFFF',
  'casa-de-artista-suites-penedo': '#18181B',
  'pousada-da-praca-penedo': '#18181B',
  'pousada-bela-vista-penedo': '#653332',
  'pousada-chales-mon-desir': '#02290C',
  'chales-laco-e-no': '#18181B',
  'hotel-moradas-do-penedo': '#8C7436',
  'hotel-aromas-de-penedo': '#FEFEFE',
  'city-park-hotel': '#FFFFFF',
  'hotel-do-papai-noel': '#8E3017',
  'pousada-penedo-house': '#FFFFFF',
  'pousada-nossa-senhora': '#000000',
  'hotel-pequena-suecia': '#F2EDE7',
  'pousada-vale-do-ermitao': '#DADDD4',
  'pousada-flor-de-penedo': '#FFFFFF',
  'pousada-vale-das-flores': '#F2BBBE',
  'pousada-das-acerolas': '#FFFFFF',
  'paris-hostelli': '#FFFFFF',
  'pousada-recanto-de-moria': '#F2EDE7',
  'aglio-e-olio': '#FFFFFF',
  'bazzini-pizzeria': '#02403B',
  'borbulha-penedo': '#854045',
  'botegare': '#5F391C',
  'braseiro-gaucho': '#4E080B',
  'casa-do-fritz': '#A50F10',
  'chocolate-do-papai-noel': '#FFFFFF',
  'enoteca-serrana': '#FFFFFF',
  'estancia-penedo': '#FFFFFF',
  'jardim-secreto': '#565445',
  'jazz-village': '#E1AF70',
  'kaiten-sushi': '#FFFFFF',
  'loazo-resto': '#ACA593',
  'petit-gourmet': '#F9FAFC',
  'querencia': '#3A3A3C',
  'rei-das-trutas': '#F9FAF4',
  'restaurante-finlandes': '#7A1115',
  'restaurante-toa-toa': '#000000',
  'truta-viva': '#FFF9AD',
  'zero-a-zero': '#FFFFFF',
  'tonttulakki-suklaat': '#542200',
  'lugano-penedo': '#C5BAAB',
  'lolita-penedo': '#FDFDFF',
  'kahvila-cafe': '#431909',
  'santa-claus-burger': '#FFFFFF',
  'maria-cuisine': '#1E1E1E',
  'vanilla-patisserie': '#84BD9A',
  'delicias-da-carol': '#FFFFFF',
  'fue-gelateria': '#FFFFFF',
  'cafe-finlandes-penedo': '#D1E5FE',
  'andicaro-penedo-cafes-especiais': '#FFFFFF',
  'emporio-chamoun': '#1C1917',
  'culto-cafe': '#FFFFFF',
  'cantinho-mineiro-tia-lili': '#FFFFFF',
  'esquina-da-serra': '#FFFFFF',
  'quatro-marias-boulangerie': '#0D476D',
  'grao-padaria-penedo': '#FFFFFF',
  'rei-da-villa': '#FFFFFF',
  'azia-sushi-lounge': '#000000',
  'bistro-du-cheff': '#FF9C06',
  'sorvete-de-penedo': '#FEFEFE',
  'sorvete-finlandes': '#3F3F97',
  'acailandia-penedo': '#000000',
  'pe-de-canela-buteco': '#FFE2A0',
  'guela-seca': '#010100',
  'janela-divino': '#FFFFFF',
  'armazem-da-vila': '#FC7F3D',
  'geek-penedo': '#131F37',
  'astral-exotheryca': '#FA0300',
  'casa-dos-cristais': '#F2F3ED',
  'via-lactea-balas': '#000000',
  'arte-da-nossa-terra': '#E8DDA7',
  'casa-das-pedras': '#FBFAF5',
  'reserva-da-mata': '#000000',
  'bufallo-couros': '#656C7E',
  'meu-sonho': '#FFFFFF',
  'artevelas': '#FDD9A5',
  'raio-de-luz-decoracoes': '#011D7E',
  'emporio-haru': '#FFFFFF',
  'rosana-balas-coco': '#FFFFFF',
  'from-penedo-delicatessen': '#FFFFFF',
  'unica-arte-para-voce': '#FFFFFF',
};

interface CardLogoPresentation {
  backgroundColor: string;
  imageClassName: string;
}

const CREAM_LOGO_CANVAS = '#F2EDE7';

export const CARD_LOGO_PRESENTATION_BY_ID: Readonly<Record<string, CardLogoPresentation>> = {
  'pousada-do-sol': {
    backgroundColor: CREAM_LOGO_CANVAS,
    imageClassName: 'h-full w-full scale-[1.55] object-contain object-center mix-blend-multiply group-hover:scale-[1.60]',
  },
  'pousada-da-praca-penedo': {
    backgroundColor: CREAM_LOGO_CANVAS,
    imageClassName: 'h-full w-full scale-[0.78] object-contain object-center mix-blend-multiply group-hover:scale-[0.81]',
  },
  'casa-de-artista-suites-penedo': {
    backgroundColor: CREAM_LOGO_CANVAS,
    imageClassName: 'h-full w-full scale-[0.78] object-contain object-center mix-blend-multiply group-hover:scale-[0.81]',
  },
  'chale-na-roca-penedo': {
    backgroundColor: CREAM_LOGO_CANVAS,
    imageClassName: 'h-full w-full scale-[0.82] object-contain object-center mix-blend-multiply group-hover:scale-[0.85]',
  },
  'chales-laco-e-no': {
    backgroundColor: CREAM_LOGO_CANVAS,
    imageClassName: 'h-full w-full scale-[0.78] object-contain object-center mix-blend-multiply group-hover:scale-[0.81]',
  },
  'pousada-finlandia': {
    backgroundColor: '#B0B5AF',
    imageClassName: 'h-full w-full object-cover object-center group-hover:scale-[1.04]',
  },
  'pousada-flor-de-penedo': {
    backgroundColor: CREAM_LOGO_CANVAS,
    imageClassName: 'h-full w-full scale-[0.82] object-contain object-center mix-blend-multiply group-hover:scale-[0.85]',
  },
  'pousada-villa-luna': {
    backgroundColor: CREAM_LOGO_CANVAS,
    imageClassName: 'h-full w-full scale-[0.88] object-contain object-center mix-blend-multiply group-hover:scale-[0.91]',
  },
  'pousada-laponia': {
    backgroundColor: CREAM_LOGO_CANVAS,
    imageClassName: 'h-full w-full scale-[1.12] object-contain object-center mix-blend-multiply group-hover:scale-[1.16]',
  },
  'pousada-doce-mel': {
    backgroundColor: '#1C0D05',
    imageClassName: 'h-full w-full scale-[0.90] object-contain object-center group-hover:scale-[0.94]',
  },
  'pousada-estancia-penedo': {
    backgroundColor: CREAM_LOGO_CANVAS,
    imageClassName: 'h-full w-full scale-[0.88] object-contain object-center mix-blend-multiply group-hover:scale-[0.91]',
  },
  'deck-pizzaria-e-choperia': {
    backgroundColor: '#E7DCC0',
    imageClassName: 'h-full w-full scale-[0.90] object-contain object-center group-hover:scale-[0.93]',
  },
  'delicias-da-carol': {
    backgroundColor: CREAM_LOGO_CANVAS,
    imageClassName: 'h-full w-full scale-[0.82] object-contain object-center mix-blend-multiply group-hover:scale-[0.85]',
  },
  'emporio-chamoun': {
    backgroundColor: CREAM_LOGO_CANVAS,
    imageClassName: 'h-full w-full scale-[0.78] object-contain object-center mix-blend-multiply group-hover:scale-[0.81]',
  },
  'farm-pizzaria': {
    backgroundColor: '#020202',
    imageClassName: 'h-full w-full scale-[0.90] object-contain object-center group-hover:scale-[0.94]',
  },
  'oh-baba-pizza-e-esfiha': {
    backgroundColor: '#010101',
    imageClassName: 'h-full w-full scale-[0.86] object-contain object-center group-hover:scale-[0.90]',
  },
};
